backend:
  name: git-gateway
  branch: main

media_folder: "assets/images"
public_folder: "images"

collections:
  - name: "writing"
    label: "Writing"
    folder: ""
    create: true
    slug: "{{year}}-{{slug}}"
    fields:
      - {label: "Title", name: 'title', widget: "string", required: true}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - { label: 'Color', name: 'color', widget: 'color', enableAlpha: true, allowInput: true }
